### ISSUE TITLE
Question: How to italicize method calls?

### ISSUE THREAD

**Issue by zeitchef** [thanhvule0310/dotfiles#3]
Thanks for sharing your dotfiles - very inspiring! Something I can't quite figure out is how you've set up method calls to be in the italicized font. I see your setting a specific italic font in the `kitty.conf` but are you using treesitter for this? If so, would you mind pointing me towards the relevant configs? Thanks!

**Comment by thanhvule0310** [comment]
Hi! I am using [onenord.nvim](https://github.com/rmehri01/onenord.nvim) theme. It has an option to
make some contexts italic.

```lua
require("onenord").setup {
    styles = {
        comments = "italic",
        strings = "NONE",
        keywords = "NONE",
        functions = "italic",
        variables = "bold",
        diagnostics = "underline",
    },
}
```

or you can come up with your own definition:

- lua

```lua
vim.highlight.create("TSFunction", { gui = "italic" }, false)
vim.highlight.create("TSFuncBuiltin", { gui = "italic" }, false)
```

- vim

```vim
highlight TSFunction gui=italic
highlight TSFuncBuiltin gui=italic
```

**Comment by thanhvule0310** [comment]
or It could also be a [kitty or font](https://github.com/kovidgoyal/kitty/issues/1648) issue.

**Comment by zeitchef** [comment]
Ah, cool - I'm also using the onenord theme, so I'll give it a try. Thanks!
