### ISSUE TITLE
How to configure CPU and MEM in tmux statusline?

### ISSUE THREAD

**Issue by zeitchef** [thanhvule0310/dotfiles#5]
I can't figure out how you have configured showing CPU and MEM in your Tmux status line (as shown in the screenshot in the README). Would you mind sharing how you do this? Thanks!

**Comment by thanhvule0310** [comment]
[tmux-cpu](https://github.com/tmux-plugins/tmux-cpu).

**Comment by zeitchef** [comment]
Cheers, thanks!
